package bench

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import kotlinx.coroutines.Dispatchers
import org.jetbrains.exposed.v1.core.Table
import org.jetbrains.exposed.v1.core.ResultRow
// `Query.where` takes a Function0, not a lambda with a builder as its receiver, so the comparison
// operators have to be in scope by import. In 1.4.0 they are top-level functions: the
// `SqlExpressionBuilder` object every tutorial still imports from is deprecated, and with warnings
// as errors that idiom does not compile.
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.jdbc.Database
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.transactions.suspendTransaction
import kotlinx.coroutines.withContext

/**
 * The data layer of the fifth phase (docs/research/research-jit-constructs.md), in the brief's two
 * modes: `real` goes to PostgreSQL through Exposed's DSL over JDBC, `stub` returns rows that were
 * built at startup.
 *
 * The stub is not a fake database. It is the same handler, the same serialisation and the same
 * response, with the query removed — which is what makes the difference between the two modes the
 * cost of the data layer rather than the cost of a different code path.
 */
interface ItemRepository {
    suspend fun byId(id: Long): Item?

    suspend fun page(limit: Int): List<Item>

    suspend fun create(new: NewItem): Item
}

/** Rows built once, at startup. No query, no pool, no driver: the CPU path without the wait. */
class StubItemRepository(rows: Int = 200) : ItemRepository {
    private val items: List<Item> =
        (1..rows).map { i ->
            Item(i.toLong(), "SKU-%04d".format(i), "item $i", i * 1.5, listOf("a", "b"))
        }

    override suspend fun byId(id: Long): Item? = items.getOrNull(((id - 1) % items.size).toInt())

    override suspend fun page(limit: Int): List<Item> = items.take(limit)

    // Returns a row of the right shape without keeping it. A stub that accumulated would make the
    // stand drift between runs, and drift inside one variant reads as noise between variants.
    override suspend fun create(new: NewItem): Item =
        Item(items.size + 1L, new.sku, new.name, new.price, new.tags)
}

object Items : Table("items") {
    val id = long("id").autoIncrement()
    val sku = varchar("sku", 32)
    val name = varchar("name", 128)
    val price = double("price")

    // A joined string rather than an array column on purpose: the brief pins "Exposed DSL over
    // JDBC", and an array type would put a vendor-specific column type on the path that most
    // services do not have.
    val tags = varchar("tags", 256)

    override val primaryKey = PrimaryKey(id)
}

class ExposedItemRepository(private val db: Database) : ItemRepository {
    // The thread hop is written out rather than passed to the transaction as a context: JDBC
    // blocks, `suspendTransaction` has no dispatcher parameter of its own, and the brief measures
    // this hop in order to subtract it - which is easier when it is its own frame in the profile.
    // (`newSuspendedTransaction(Dispatchers.IO, db)`, the shape every tutorial shows, is deprecated
    // in 1.4.0.)
    override suspend fun byId(id: Long): Item? =
        withContext(Dispatchers.IO) {
            suspendTransaction(db = db) {
                Items.selectAll().where { Items.id eq id }.limit(1).map(::toItem).firstOrNull()
            }
        }

    override suspend fun page(limit: Int): List<Item> =
        withContext(Dispatchers.IO) {
            suspendTransaction(db = db) {
                Items.selectAll().orderBy(Items.id).limit(limit).map(::toItem)
            }
        }

    override suspend fun create(new: NewItem): Item =
        withContext(Dispatchers.IO) {
            suspendTransaction(db = db) {
                val row =
                    Items.insert {
                        it[sku] = new.sku
                        it[name] = new.name
                        it[price] = new.price
                        it[tags] = new.tags.joinToString(",")
                    }
                Item(row[Items.id], new.sku, new.name, new.price, new.tags)
            }
        }

    private fun toItem(row: ResultRow): Item =
        Item(
            row[Items.id],
            row[Items.sku],
            row[Items.name],
            row[Items.price],
            row[Items.tags].let { if (it.isEmpty()) emptyList() else it.split(",") },
        )
}

/**
 * Opens the pool and makes sure the table exists with [seed] rows.
 *
 * The schema is raw DDL rather than `SchemaUtils.create`: it is four columns that never change, and
 * a stand whose schema is generated by the library it measures cannot be read without the library.
 */
fun connectPostgres(
    url: String,
    user: String,
    password: String,
    poolSize: Int,
    seed: Int,
): Database {
    val cfg =
        HikariConfig().apply {
            jdbcUrl = url
            username = user
            this.password = password
            maximumPoolSize = poolSize
            // The pool is sized by the stand, not by Hikari's default of ten: the pool size is a
            // variable of any measurement that goes through it, so it is written down and printed.
            poolName = "bench"
            isAutoCommit = false
        }
    val ds = HikariDataSource(cfg)
    ds.connection.use { c ->
        c.createStatement().use { s ->
            s.execute(
                """
                CREATE TABLE IF NOT EXISTS items (
                  id    BIGSERIAL PRIMARY KEY,
                  sku   VARCHAR(32)  NOT NULL,
                  name  VARCHAR(128) NOT NULL,
                  price DOUBLE PRECISION NOT NULL,
                  tags  VARCHAR(256) NOT NULL
                )
                """.trimIndent(),
            )
        }
        c.createStatement().use { s ->
            s.executeQuery("SELECT count(*) FROM items").use { rs ->
                rs.next()
                val have = rs.getLong(1)
                if (have < seed) {
                    c.prepareStatement(
                        "INSERT INTO items (sku, name, price, tags) VALUES (?, ?, ?, ?)",
                    ).use { ps ->
                        for (i in (have + 1)..seed) {
                            ps.setString(1, "SKU-%04d".format(i))
                            ps.setString(2, "item $i")
                            ps.setDouble(3, i * 1.5)
                            ps.setString(4, "a,b")
                            ps.addBatch()
                        }
                        ps.executeBatch()
                    }
                }
            }
        }
        c.commit()
    }
    return Database.connect(ds)
}
